services:
  server:
    build:
      context: ./frontend/vite-project
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./frontend/vite-project/package.json
          action: rebuild
        - path: ./frontend/vite-project
          target: /usr/src/app
          action: sync
