version: "3.9"

services:
  postgres:
    container_name: postgres-urbanize
    image: "bitnami/postgresql:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api-urbanize
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: